/**
 * Government-scheme catalogue accessor.
 *
 * The catalogue is a static, committed JSON file generated by
 * `scripts/extract-scheme-criteria.mjs`, so reads are in-memory and instant — no
 * DynamoDB scan needed for the (rarely-changing) scheme list.
 */
import schemesData from '@/lib/data/tn-schemes.json';
import type { Scheme } from './types';

const SCHEMES = schemesData as unknown as Scheme[];

export function getAllSchemes(): Scheme[] {
  return SCHEMES;
}

export function getScheme(idOrSlug: string): Scheme | undefined {
  return SCHEMES.find((s) => s.id === idOrSlug || s.slug === idOrSlug);
}
