/**
 * Government-scheme catalogue types.
 *
 * Each scheme keeps its human-readable myScheme content (benefits, eligibility,
 * how-to-apply, documents) PLUS a structured `criteria` object distilled from the
 * free-text eligibility. The criteria are what the matcher evaluates against a
 * farmer's profile to decide whether they are eligible.
 *
 * Catalogue is generated by `scripts/extract-scheme-criteria.mjs` into
 * `lib/data/tn-schemes.json`.
 */

export type SchemeLevel = 'State' | 'Central';

/** Indian land-holding classes, derived from acreage. */
export type LandSizeClass = 'marginal' | 'small' | 'semi-medium' | 'medium' | 'large';

export type Gender = 'female' | 'male';

/** Social community categories used in scheme eligibility. */
export type Community = 'SC' | 'ST' | 'Tribal' | 'BC' | 'MBC' | 'DNC' | 'Minority' | 'General';

/**
 * Structured eligibility filters. A `null`/`[]` value means "this scheme does not
 * restrict on that field" (i.e. anyone passes it). Only set a field when the
 * scheme's eligibility text actually states the restriction.
 */
export interface SchemeCriteria {
  level: SchemeLevel;
  /** Occupations the scheme targets, e.g. ['Farmer'], ['Fishermen']. Empty = any. */
  occupations: string[];
  /** TN districts the scheme is limited to; null = all of Tamil Nadu / not limited. */
  districts: string[] | null;
  /** Crops the scheme is tied to (e.g. ['Maize'], ['Pulses']); null = any crop. */
  crops: string[] | null;
  /** Preferred/eligible land-holding classes; null = any. Treated as a soft preference. */
  landSizeClass: LandSizeClass[] | null;
  /** Eligible communities; null = any. */
  communities: Community[] | null;
  /** True when communities are only a stated *preference* (not a hard requirement). */
  communityIsPreferenceOnly: boolean;
  /** Required gender; null = any. */
  gender: Gender | null;
  ageMin: number | null;
  ageMax: number | null;
  /** Hard annual-income cap in ₹, if the scheme states one; null = none. */
  incomeMaxAnnual: number | null;
  /** Conditions that couldn't be structured (e.g. "must supply certified seeds"). */
  otherConditions: string[];
}

export interface SchemeReference {
  title: string;
  url: string;
}

export interface SchemeProcess {
  mode: string;
  md: string;
}

export interface Scheme {
  /** Stable id (myScheme slug). */
  id: string;
  slug: string;
  name: string;
  shortTitle?: string;
  level: SchemeLevel;
  /** 'Tamil Nadu' for state schemes; '' for Central. */
  state: string;
  department?: string;
  category?: string;
  subCategory?: string;
  brief?: string;
  benefits: string;
  eligibility: string;
  exclusions?: string;
  process: SchemeProcess[];
  documents?: string;
  references: SchemeReference[];
  criteria: SchemeCriteria;
}

/** Facts about a farmer the matcher evaluates against scheme criteria. */
export interface FarmerFacts {
  district?: string | null;
  landAreaAcres?: number | null;
  /** Crops the farmer grows/plans (from crop plans, profile or memory). */
  crops?: string[];
  /** Social community (SC/ST/...); NOT the land-size category. */
  community?: string | null;
  gender?: Gender | null;
  age?: number | null;
  annualIncome?: number | null;
}

export type MatchStatus = 'eligible' | 'likely' | 'check';

export interface SchemeMatch {
  scheme: Scheme;
  status: MatchStatus;
  /** Human-readable reasons the scheme fits this farmer. */
  matchedOn: string[];
  /** Conditions the farmer still needs to confirm / provide. */
  unknownConditions: string[];
  /** Sort score (higher = more relevant). */
  score: number;
}
